<Project Sdk="MSTest.Sdk/3.6.4">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseVSTest>true</UseVSTest>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NSubstitute" Version="5.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wup.Works.SiteBroker.Client\Wup.Works.SiteBroker.Client.csproj" />
	</ItemGroup>

</Project>
